import type { PartidoData } from '../types'

/** 14 partidos de ejemplo — Jornada 42, Mayo 2026 */
export const PARTIDOS: PartidoData[] = [
  {
    id: 1,
    local: 'Real Madrid',
    visitante: 'Barcelona',
    dia: 'Sáb 16',
    hora: '21:00',
    escudoLocal: '⚪',
    escudoVisitante: '🔵',
    h2h: { local: 3, empate: 0, visitante: 2 },
    formaLocal: ['V', 'V', 'E', 'V', 'V'],
    formaVisitante: ['V', 'E', 'V', 'V', 'V'],
    momio: { uno: 2.1, equis: 3.5, dos: 3.2 },
    dificultad: 'amarillo',
  },
  {
    id: 2,
    local: 'Atlético Madrid',
    visitante: 'Sevilla',
    dia: 'Sáb 16',
    hora: '18:30',
    escudoLocal: '🔴',
    escudoVisitante: '⚪',
    h2h: { local: 2, empate: 2, visitante: 1 },
    formaLocal: ['V', 'V', 'V', 'D', 'V'],
    formaVisitante: ['E', 'D', 'V', 'E', 'D'],
    momio: { uno: 1.7, equis: 3.8, dos: 4.5 },
    dificultad: 'verde',
  },
  {
    id: 3,
    local: 'Athletic Club',
    visitante: 'Real Sociedad',
    dia: 'Dom 17',
    hora: '14:00',
    escudoLocal: '🔴',
    escudoVisitante: '🔵',
    h2h: { local: 1, empate: 3, visitante: 1 },
    formaLocal: ['V', 'E', 'V', 'E', 'V'],
    formaVisitante: ['E', 'V', 'V', 'D', 'E'],
    momio: { uno: 2.4, equis: 3.1, dos: 2.9 },
    dificultad: 'rojo',
  },
  {
    id: 4,
    local: 'Betis',
    visitante: 'Valencia',
    dia: 'Dom 17',
    hora: '16:15',
    escudoLocal: '🟢',
    escudoVisitante: '🟠',
    h2h: { local: 2, empate: 1, visitante: 2 },
    formaLocal: ['D', 'V', 'E', 'V', 'D'],
    formaVisitante: ['E', 'E', 'D', 'V', 'E'],
    momio: { uno: 2.6, equis: 3.3, dos: 2.7 },
    dificultad: 'rojo',
  },
  {
    id: 5,
    local: 'Girona',
    visitante: 'Villarreal',
    dia: 'Dom 17',
    hora: '18:30',
    escudoLocal: '🔴',
    escudoVisitante: '🟡',
    h2h: { local: 1, empate: 4, visitante: 0 },
    formaLocal: ['V', 'V', 'D', 'V', 'E'],
    formaVisitante: ['D', 'V', 'V', 'E', 'V'],
    momio: { uno: 2.3, equis: 3.4, dos: 2.8 },
    dificultad: 'amarillo',
  },
  {
    id: 6,
    local: 'Celta',
    visitante: 'Osasuna',
    dia: 'Dom 17',
    hora: '21:00',
    escudoLocal: '🔵',
    escudoVisitante: '🔴',
    h2h: { local: 2, empate: 2, visitante: 1 },
    formaLocal: ['E', 'D', 'V', 'E', 'V'],
    formaVisitante: ['V', 'E', 'D', 'V', 'E'],
    momio: { uno: 2.2, equis: 3.2, dos: 3.1 },
    dificultad: 'amarillo',
  },
  {
    id: 7,
    local: 'Mallorca',
    visitante: 'Getafe',
    dia: 'Lun 18',
    hora: '20:00',
    escudoLocal: '🔴',
    escudoVisitante: '🔵',
    h2h: { local: 3, empate: 1, visitante: 1 },
    formaLocal: ['V', 'D', 'E', 'V', 'D'],
    formaVisitante: ['E', 'E', 'E', 'D', 'E'],
    momio: { uno: 2.0, equis: 3.1, dos: 3.8 },
    dificultad: 'verde',
  },
  {
    id: 8,
    local: 'Las Palmas',
    visitante: 'Espanyol',
    dia: 'Dom 17',
    hora: '14:00',
    escudoLocal: '🟡',
    escudoVisitante: '🔵',
    h2h: { local: 1, empate: 0, visitante: 2 },
    formaLocal: ['D', 'D', 'E', 'V', 'D'],
    formaVisitante: ['E', 'V', 'D', 'D', 'E'],
    momio: { uno: 2.9, equis: 3.3, dos: 2.4 },
    dificultad: 'rojo',
  },
  {
    id: 9,
    local: 'Rayo Vallecano',
    visitante: 'Alavés',
    dia: 'Dom 17',
    hora: '16:15',
    escudoLocal: '⚪',
    escudoVisitante: '🔵',
    h2h: { local: 2, empate: 2, visitante: 1 },
    formaLocal: ['E', 'V', 'V', 'E', 'D'],
    formaVisitante: ['D', 'E', 'D', 'V', 'E'],
    momio: { uno: 2.3, equis: 3.2, dos: 3.0 },
    dificultad: 'amarillo',
  },
  {
    id: 10,
    local: 'Leganés',
    visitante: 'Valladolid',
    dia: 'Lun 18',
    hora: '21:00',
    escudoLocal: '🔵',
    escudoVisitante: '🟣',
    h2h: { local: 1, empate: 2, visitante: 1 },
    formaLocal: ['E', 'E', 'D', 'V', 'D'],
    formaVisitante: ['D', 'D', 'D', 'E', 'E'],
    momio: { uno: 2.5, equis: 3.2, dos: 2.8 },
    dificultad: 'amarillo',
  },
  {
    id: 11,
    local: 'Manchester City',
    visitante: 'Arsenal',
    dia: 'Sáb 16',
    hora: '13:30',
    escudoLocal: '🔵',
    escudoVisitante: '🔴',
    h2h: { local: 3, empate: 1, visitante: 1 },
    formaLocal: ['V', 'V', 'V', 'V', 'E'],
    formaVisitante: ['V', 'V', 'D', 'V', 'V'],
    momio: { uno: 1.8, equis: 3.7, dos: 4.2 },
    dificultad: 'amarillo',
  },
  {
    id: 12,
    local: 'Inter',
    visitante: 'AC Milan',
    dia: 'Dom 17',
    hora: '20:45',
    escudoLocal: '⚫',
    escudoVisitante: '🔴',
    h2h: { local: 3, empate: 0, visitante: 2 },
    formaLocal: ['V', 'V', 'E', 'V', 'V'],
    formaVisitante: ['V', 'D', 'V', 'V', 'E'],
    momio: { uno: 2.0, equis: 3.4, dos: 3.6 },
    dificultad: 'verde',
  },
  {
    id: 13,
    local: 'PSG',
    visitante: 'Mónaco',
    dia: 'Dom 17',
    hora: '21:00',
    escudoLocal: '🔵',
    escudoVisitante: '🔴',
    h2h: { local: 4, empate: 0, visitante: 1 },
    formaLocal: ['V', 'V', 'V', 'E', 'V'],
    formaVisitante: ['V', 'E', 'V', 'D', 'V'],
    momio: { uno: 1.6, equis: 4.2, dos: 5.0 },
    dificultad: 'verde',
  },
  {
    id: 14,
    local: 'Boca Juniors',
    visitante: 'River Plate',
    dia: 'Dom 17',
    hora: '22:30',
    escudoLocal: '🔵',
    escudoVisitante: '⚪',
    h2h: { local: 1, empate: 3, visitante: 1 },
    formaLocal: ['E', 'V', 'V', 'D', 'E'],
    formaVisitante: ['V', 'V', 'E', 'V', 'V'],
    momio: { uno: 2.8, equis: 3.1, dos: 2.5 },
    dificultad: 'rojo',
  },
]
